### ISSUE TITLE
Agregar color visible en card evento hover

### ISSUE THREAD

**Issue by FedeHerrera10** [GuzH09/GuzHPortfolio#2]
Primero que nada quiero sumar a tu portofilio.
Cuando se hace hover sobre cada card no se ve el texto.
Para ello se puede agregar en el div padre la clase text-slate-200 o
algun color claro dado que no se ve por el color negro.

**Comment by GuzH09** [comment]
Estabas usando algun navegador particular? Te referis a esto?
![image](https://github.com/user-attachments/assets/71f99f16-69b2-4f02-a0a9-9efda34e07e7)

**Comment by FedeHerrera10** [comment]
![image](https://github.com/user-attachments/assets/0500cd22-3992-4278-8947-6bb20ca1ab32)

Aqui no se cuando se hace hover sobre la card. Estoy usando chrome

**Comment by GuzH09** [comment]
Arreglado! No me había percatado de que estaba usando el color de fuente por defecto y que no había establecido un valor
